---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Picture_for_Assignment2/Picture_for_Assignment2.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/249318/articles/335450/master/file/figures/Picture_for_Assignment2/Picture_for_Assignment2.png"
    folder_url: "/users/249318/articles/335450/master/folder/figures/Picture_for_Assignment2"
